# Generated by Django 3.0.8 on 2020-07-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gildrose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemType',
            field=models.CharField(default='reg', max_length=20),
        ),
    ]
