# Generated by Django 3.0.8 on 2020-07-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gildrose', '0002_item_itemtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itemType',
        ),
    ]
