# Generated by Django 3.0.8 on 2020-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gildrose', '0004_item_itemtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemType',
            field=models.CharField(choices=[('AgedBrie', 'AgedBrie'), ('Sulfuras', 'Sulfuras'), ('REG', 'REG'), ('Backstage', 'Backstage'), ('Conjured', 'Conjured')], default='REG', max_length=20),
        ),
    ]
